# /Monitoring/k8s-local/03-elasticsearch.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# 2. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true

      containers:
        # [수정 1] Elasticsearch 리소스 대폭 상향
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.enrollment.enabled
              value: "false"
            # 외부 접속 허용 (localhost 외 접근 가능)
            - name: network.host
              value: "0.0.0.0"
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              # 컨테이너 메모리는 힙(1GB)보다 커야 함. 2GB 추천.
              memory: "2Gi"
              cpu: "1000m"

        # Exporter (변경 없음)
        - name: elasticsearch-exporter
          image: prometheuscommunity/elasticsearch-exporter:latest
          args:
            - '--es.uri=http://localhost:9200'
            - '--es.all'
            - '--es.indices'
          ports:
            - containerPort: 9114
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc

---
# 3. Service (변경 없음)
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: monitoring
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920
      name: http
    - port: 9114
      targetPort: 9114
      name: metrics

---
# 4. Kibana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        # [수정 2] Kibana 리소스 및 타임아웃 상향
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.encryptedSavedObjects.encryptionKey
              value: "min-32-byte-long-strong-encryption-key"
            - name: SERVER_NAME
              value: "kibana"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: NODE_OPTIONS
              value: "--max-old-space-size=400"   # 기존 1024MB -> 400MB로 줄여서 OOM Kill 방지
            - name: XPACK_MONITORING_ENABLED      # 자체 모니터링 비활성화 (CPU/메모리 절약)
              value: "false"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              # 컨테이너 메모리 한계 상향 (기존 512Mi -> 1.5Gi)
              memory: "512Mi"
              cpu: "500m"

          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 20   # 체크 주기 늘림
            timeoutSeconds: 10  # 타임아웃 늘림
            failureThreshold: 10 # 실패 허용 횟수 늘림
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 180 # 초기 대기 시간 대폭 증가
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5

---
# 5. Kibana Service (변경 없음)
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: monitoring
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601
      name: http
  type: NodePort