# /Monitoring/k8s-local/03-elasticsearch.yaml

# ==========================================
# 1. PersistentVolume (데이터 영구 저장소)
# ==========================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # PV 삭제되어도 데이터 파일은 보존
  storageClassName: manual
  hostPath:
    path: /tmp/k8s-data/elasticsearch
    type: DirectoryOrCreate

---
# 2. PersistentVolumeClaim (볼륨 요청)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi

---
# 3. Elasticsearch Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      # [필수] 권한 및 커널 설정
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true

      containers:
        # [메인] Elasticsearch
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"  # 힙 메모리 1GB 고정
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.enrollment.enabled
              value: "false"
            - name: network.host
              value: "0.0.0.0"
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              memory: "1Gi"   # 최소 확보
              cpu: "500m"
            limits:
              memory: "2Gi"   # 최대 허용 (힙 1GB + OS 여유분)
              cpu: "1000m"

        # [보조] Exporter
        - name: elasticsearch-exporter
          image: prometheuscommunity/elasticsearch-exporter:latest
          args:
            - '--es.uri=http://localhost:9200'
            - '--es.all'
            - '--es.indices'
          ports:
            - containerPort: 9114
              name: metrics
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc

---
# 4. Elasticsearch Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: monitoring
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920
      name: http
    - port: 9114
      targetPort: 9114
      name: metrics

---
# 5. Kibana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch-service:9200"
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.encryptedSavedObjects.encryptionKey
              value: "min-32-byte-long-strong-encryption-key"
            - name: SERVER_NAME
              value: "kibana"
            - name: SERVER_HOST
              value: "0.0.0.0"
            # [최적화] Node.js 힙 메모리 제한 (OS OOM 방지)
            - name: NODE_OPTIONS
              value: "--max-old-space-size=512"
            # [최적화] 불필요한 기능 OFF
            - name: XPACK_MONITORING_ENABLED
              value: "false"
            - name: TELEMETRY_ENABLED
              value: "false"

          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              # [중요] Node 옵션(512MB)보다 넉넉하게 잡아야 안 죽습니다.
              memory: "1Gi"
              cpu: "1000m"

          # [안정성] 느린 부팅을 기다려주는 설정
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 15
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 180  # 3분 대기 (부팅 시간 확보)
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5

---
# 6. Kibana Service
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: monitoring
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601
      name: http
  type: NodePort