# /Monitoring/k8s-local/05-eng-study-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eng-study-backend
  namespace: eng-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eng-study-backend
  template:
    metadata:
      labels:
        app: eng-study-backend
    spec:
      containers:
        - name: eng-study-backend
          image: eng-study:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # 데이터베이스 연결 설정
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/DEV_DB"
            - name: SPRING_DATASOURCE_USERNAME
              value: "rnbsoft"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "rnbsoft"
            # Elasticsearch 연결 설정
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch-service"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            # 프로파일 설정
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90     # 60 → 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60     # 30 → 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: eng-study-backend-service
  namespace: eng-study
spec:
  selector:
    app: eng-study-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
