# /Monitoring/k8s-local/07-monitoring-backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-backend
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-backend
  template:
    metadata:
      labels:
        app: monitoring-backend
    spec:
      containers:
        - name: monitoring-backend
          image: study-monitoring:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            # PostgreSQL 연결 (eng-study namespace의 DB 사용)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.eng-study.svc.cluster.local:5432/DEV_DB"
            - name: SPRING_DATASOURCE_USERNAME
              value: "rnbsoft"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "rnbsoft"
            # Elasticsearch 연결 (같은 namespace)
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch-service"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx200m -XX:+UseSerialGC -XX:TieredStopAtLevel=1"
          resources:
            requests:
              memory: "200Mi"   # 기존 512Mi -> 200Mi로 축소
              cpu: "100m"
            limits:
              memory: "350Mi"   # 기존 1Gi -> 350Mi로 축소
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-backend-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: monitoring-backend