# /Monitoring/k8s-local/08-monitoring-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-frontend
  namespace: eng-study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring-frontend
  template:
    metadata:
      labels:
        app: monitoring-frontend
    spec:
      containers:
        - name: monitoring-frontend
          image: study-monitoring-frontend:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-frontend-service
  namespace: eng-study
spec:
  selector:
    app: monitoring-frontend
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
