apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: monitoring
data:
  logstash.conf: |
    input {
      file { path => "/usr/share/logstash/pipeline/logs/application.log" start_position => "beginning" codec => json tags => ["app_log"] }
      file { path => "/usr/share/logstash/pipeline/logs/error.log" start_position => "beginning" codec => json tags => ["error_log"] }
      file { path => "/usr/share/logstash/pipeline/logs/access.log" start_position => "beginning" codec => json tags => ["access_log"] }
      file { path => "/usr/share/logstash/pipeline/logs/audit.log" start_position => "beginning" codec => json tags => ["audit_log"] }
      file { path => "/usr/share/logstash/pipeline/logs/performance.log" start_position => "beginning" codec => json tags => ["perf_log"] }
      file { path => "/usr/share/logstash/pipeline/logs/database.log" start_position => "beginning" codec => json tags => ["db_log"] }
      file { path => "/usr/share/logstash/pipeline/logs/security.log" start_position => "beginning" codec => json tags => ["sec_log"] }
    }

    filter {
      # ======================================================
      # ✅ [최적화] 1단계: 불필요한 로그 즉시 삭제 (리소스 절약)
      # ======================================================
      # 1. Kubernetes Health Check (Probe) 로그 삭제
      # 2. Prometheus 및 Actuator 헬스 체크 로그 삭제
      # 3. 정적 파일(이미지, CSS 등) 요청 로그 삭제
      if [message] =~ "kube-probe" or [user_agent] =~ "kube-probe" { drop { } }
      if [message] =~ "/actuator/health" or [message] =~ "/actuator/prometheus" { drop { } }
      if [message] =~ "\.(css|js|png|jpg|ico|woff|ttf)" { drop { } }

      # ======================================================
      # 2단계: 필수 로그 가공 및 정제
      # ======================================================
      # 타임스탬프 처리
      date {
        match => [ "timestamp", "ISO8601", "yyyy-MM-dd HH:mm:ss.SSS", "yyyy-MM-dd'T'HH:mm:ss.SSSZ" ]
        target => "@timestamp"
        timezone => "Asia/Seoul"
      }

      # ------------------------------------------------------
      # Security Log - JSON 신뢰 모드
      # ------------------------------------------------------
      if "sec_log" in [tags] {
    
        # 1. Threat Level 처리
        if ![security][threat_level] {
          if [mdc][threat_level] {
             mutate { add_field => { "[security][threat_level]" => "%{[mdc][threat_level]}" } }
          } else if [threat_level] {
             mutate { add_field => { "[security][threat_level]" => "%{threat_level}" } }
          } else {
             # 기본값
             mutate { add_field => { "[security][threat_level]" => "low" } }
          }
        }
        mutate { lowercase => [ "[security][threat_level]" ] }

        # 2. Log Level 조정
        if [security][threat_level] == "critical" {
          mutate { replace => { "log_level" => "CRITICAL" } }
        } else if [security][threat_level] == "high" {
          mutate { replace => { "log_level" => "ERROR" } }
        } else if [security][threat_level] == "medium" {
          mutate { replace => { "log_level" => "WARN" } }
        }

        # ======================================================
        # ✅ [핵심 추가] Blocked(차단) 여부 판단 로직
        # ======================================================
        # 메시지에 "Block", "Deny", "Refused"가 있거나, 레벨이 높으면 차단된 것으로 간주
    
        if [message] =~ /(?i)(Block|Deny|Refused|Forbidden|Access is denied)/ {
            mutate { add_field => { "blocked" => true } }
        } 
        else if [log_level] in ["ERROR", "CRITICAL", "FATAL"] {
            # 에러/심각 레벨은 보통 차단되거나 실패한 공격임
            mutate { add_field => { "blocked" => true } }
        } 
        else {
            # 그 외(INFO, WARN)은 허용된 접근이나 단순 경고
            mutate { add_field => { "blocked" => false } }
        }

        # ⚠️ 중요: Elasticsearch가 boolean으로 인식하도록 형변환
        mutate {
            convert => { "blocked" => "boolean" }
        }
      }

      # ------------------------------------------------------
      # Database Log - 쿼리 성능 분석
      # ------------------------------------------------------
      if "db_log" in [tags] {
        if [logger] { mutate { copy => { "logger" => "logger_name" } } }
        if [level] { mutate { copy => { "level" => "log_level" } } }

        # ✅ [수정] duration_ms 처리 강화
        # Logback에서 넘어온 JSON에 'duration_ms'가 있다면 숫자로 변환
        if [duration_ms] {
          mutate {
            # 1. integer로 변환
            convert => { "duration_ms" => "integer" }
          }
          mutate {
             # 2. query 객체 하위로 이동 (Elasticsearch 스키마 구조화)
             rename => { "duration_ms" => "[query][duration_ms]" }
          }
        }
    
        # ERROR 레벨이면 에러 태그 추가
        if [log_level] == "ERROR" {
          mutate { add_tag => [ "db_error", "error_log" ] }
        }
      }

      # ------------------------------------------------------
      # Audit Log - 사용자 행위 분석
      # ------------------------------------------------------
      if "audit_log" in [tags] {
        ruby {
          code => '
            event.set("[event][action]", "general")
            event.set("[event][category]", "general")
            event.set("[event][result]", "success")
          '
        }
    
        if [message] =~ /login.*success/ {
          ruby { code => 'event.set("[event][action]", "user.login")' }
        } else if [message] =~ /logout/ {
          ruby { code => 'event.set("[event][action]", "user.logout")' }
        }
      }

      # ------------------------------------------------------
      # 공통: 불필요한 필드 제거 (용량 절약)
      # ------------------------------------------------------
      mutate {
        remove_field => [ "log", "event", "host", "@version", "path" ]
      }
    }

    output {
      # 1. DB 에러 (중요하므로 Error 인덱스에도 저장)
      if "db_error" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "database-logs-%{+YYYY.MM.dd}" }
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "error-logs-%{+YYYY.MM.dd}" }
      }
      # 2. Security (보안)
      else if "sec_log" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "security-logs-%{+YYYY.MM.dd}" }
      }
      # 3. Application (일반)
      else if "app_log" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "application-logs-%{+YYYY.MM.dd}" }
      }
      # 4. Error (에러)
      else if "error_log" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "error-logs-%{+YYYY.MM.dd}" }
      }
      # 5. DB (일반)
      else if "db_log" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "database-logs-%{+YYYY.MM.dd}" }
      }
      # 6. Audit (감사)
      else if "audit_log" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "audit-logs-%{+YYYY.MM.dd}" }
      }
      # 7. Access (접속)
      else if "access_log" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "access-logs-%{+YYYY.MM.dd}" }
      }
      # 8. Performance (성능)
      else if "perf_log" in [tags] {
        elasticsearch { hosts => ["elasticsearch-service:9200"] index => "performance-metrics-%{+YYYY.MM.dd}" }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.11.0
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 9600
              name: api
          env:
            # ✅ [M1 최적화] JVM 힙 메모리 256MB로 제한 (이 정도면 충분합니다)
            - name: LS_JAVA_OPTS
              value: "-Xmx256m -Xms256m"
            - name: XPACK_MONITORING_ENABLED
              value: "false"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              # ✅ [M1 최적화] 컨테이너가 512MB 이상 못 쓰게 제한
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
            - name: shared-logs
              mountPath: /usr/share/logstash/pipeline/logs
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
        - name: shared-logs
          hostPath:
            path: /tmp/k8s-logs
            type: DirectoryOrCreate